config/routes.rb
Lotl::Application.routes.draw do

  get "whatsandwhys" => 'info#whatsandwhys', :as => 'whats_and_whys'

  match "/home" => 'entrance#home', :via => 'get', :as => 'home'
  match "/login" => 'entrance#login', :via => 'post', :as => 'login'
  match "/activation_instructions" => "entrance#activation_instructions", :via => 'get', :as => 'activation_instructions'
  match "/activate" => "entrance#activate", :via => 'get', :as => 'activate'

  resources :users, :only => [:new, :create]
  resources :feedback, :only => [:new, :create]

  resources :projects do
    resources :tasks
    resources :collaborators, :only => [:create, :destroy]
    resources :statistics, :only => [:index, :show]
  end

  root :to => "entrance#home"

end

app/controllers/entrance_controller.rb
class EntranceController < ApplicationController
  skip_before_filter :authenticate
  ssl_required :home, :login

  def home
    @submitted_credentials = User.new
  end

  #process a submission of the user login form
  def login
    @submitted_credentials = User.new(params)

    @user = User.find_by_email(@submitted_credentials.email)
    if @user.nil?
      @submitted_credentials.errors.add(:email, "is not a associated with a valid user")
    else
      @submitted_credentials.errors.add(:not_active, "this account must be activated before use") if @user.active == false
      @submitted_credentials.errors.add(:password, "is not valid for the given email") if not @user.is_users_password?(@submitted_credentials.password)
    end
    
    respond_to do |format|
      if (@submitted_credentials.errors.empty?) 
        self.current_user = @user
        format.html { redirect_to(projects_path) }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "home" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # this just forwards to the view which contains account activation instructions for new account
  def activation_instructions
  end

  # activates a users account
  def activate
    @user = User.new(params)
    @user.salt = params[:token]

    true_user = User.find_by_email(@user.email)
    if true_user.nil?
      @user.errors.add(:email, "the email is not registed in the system")
    else
      @user.errors.add(:token, "invalid authoization token") if true_user.salt != @user.salt
    end

    respond_to do |format|
      if @user.errors.empty?
        true_user.active = true
        true_user.save
        self.current_user = true_user
        flash[:success] = t "flash.msg.activation-success"
        format.html { redirect_to(projects_path) }
      else
        format.html { render :action => "activation_instructions" }
      end
    end
  end

  private

end


# errors: forgot to add a @ before submitted_credentials (twice)
# errors: forgot to add '@submitted_credentials' before errors.any?
# errors: I knew users could be nil comming back from the activate method but then I use it for everything and still dont see whats going on, after a rest Im see it right away
# errors: for @user i typed @use

app/helpers/entrance_helper.rb
module EntranceHelper


end

app/views/entrance/activation_instructions.html.erb
<% if (not @user.nil?) && @user.errors.any? %>
<div class="error">
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div span-8 prepend-8>
  <p>
    You have successfully registered but before you can use LOOP, you have to activate your account.
    The activation instructions have been sent to your email account.
  </p>
</div>

app/views/entrance/home.html.erb
<div class="ltl-home-brief span-17">
  <h2><%= t ".project-coordination-for-continuous-delivery" %></h2>
  <div class="ltl-home-point span-16 last append-bottom">
    <h3 class="subpoint"><%= t ".feedback" %></h3>
    <p>An organization cant evolve itself unless it can respond, recover, and experiment efficiently. LOOP gives groups
      feedback on their efficiency by measuring loop time, the time from when an effort begins when it
      it is fully usable by a recipient. Teams have to learn
      to loop with speed and quality and LOOP helps them learn by providing helpful and friendly feedback
      at the group <!-- and individual -->level.
    </p>
  </div>
<!--
  <div class="ltl-home-point span-16 last append-bottom">
    <h3><%= t ".learning" %></h3>
    <p>Working more productively is also matter of leaning to use better tools and better methods. LOOP is a
    forum to disseminate information among ourselves on what works, and to back up that information with
    data that supports it.</p>
  </div>  
-->
  <div class="ltl-home-point span-16 last">
    <h3 class="subpoint"><%= t ".freedom" %></h3>
    <p>Every methodology claims to manage successful projects, but no methodology can say in advance
    which projects it will manage successfully. LOOP doesn't promote a methodology. It provides 
    a flexible system that stays out of the way, allowing group coordination with whatever methods
    work within any particular organization.</p>
  </div>
</div>

<div class="ltl-login-form prepend-1 span-6 last">
  <h2><%= t ".sign-in" %></h2>
  <p style="text-align: center">
    <%= link_to t(".create-an-account"), new_user_path %>
  </p>
  <form action="<%= login_path %>" method="POST">

    <% if @submitted_credentials.errors.any? %>
    <div class="error">
      <ul>
	<% @submitted_credentials.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
      </ul>
    </div>
    <% end %>

    <label><%= t ".email" %>:</label><br/>
    <input class="span-6" type="text" name="email" value="<%= @submitted_credentials.email %>"/>
    <br/>
    <label><%= t ".password" %>:</label><br/>
    <input class="span-6" type="password" name="password" />
    <br/>
    <input type="submit" name="submit" value="<%= t '.sign-in' %>" />
  </form>
</div>

<%# error: ended a erb code block with a = in place of a % %>