config/routes.rb
Lotl::Application.routes.draw do

  get "whatsandwhys" => 'info#whatsandwhys', :as => 'whats_and_whys'

  match "/home" => 'entrance#home', :via => 'get', :as => 'home'
  match "/login" => 'entrance#login', :via => 'post', :as => 'login'
  match "/activation_instructions" => "entrance#activation_instructions", :via => 'get', :as => 'activation_instructions'
  match "/activate" => "entrance#activate", :via => 'get', :as => 'activate'

  resources :users, :only => [:new, :create]
  resources :feedback, :only => [:new, :create]

  resources :projects do
    resources :tasks
    resources :collaborators, :only => [:create, :destroy]
    resources :statistics, :only => [:index, :show]
  end

  root :to => "entrance#home"

end

app/models/user.rb
# == Schema Information
# Schema version: 20110703011409
#
# Table name: users
#
#  id         :integer         not null, primary key
#  password   :string(64)      not null
#  salt       :string(64)      not null
#  email      :string(255)     not null
#  created_at :datetime
#  updated_at :datetime
#
require 'digest'

class User < ActiveRecord::Base
  before_save :encrypt_password

  has_and_belongs_to_many :projects
  has_and_belongs_to_many :tasks

  attr_accessible :password, :password_confirmation, :email

  validates :email, :presence => true,
                    :format => {:with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                    :uniqueness => {:case_sensitive => false}
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..125}

  def is_users_password?(raw_pswd)
    salt = read_attribute(:salt)
    encr_pswd = read_attribute(:password)
    encr_pswd == Digest::SHA2.hexdigest(salt + raw_pswd)
  end

  private

  def encrypt_password
    if self.new_record?
      raw_pswd = read_attribute(:password)
      salt = Digest::SHA2.hexdigest(Time.now.to_s + raw_pswd)
      write_attribute(:salt, salt)

      encr_pswd = Digest::SHA2.hexdigest(salt + raw_pswd)
      write_attribute(:password, encr_pswd)
    end
  end

end

# error: forgot to add a comma between key/values in a literal map declaration

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate, :only => [:new, :create]
  ssl_required :new, :create

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        AdminMailer.activation_instructions(@user, request.host).deliver
        format.html { redirect_to(activation_instructions_path) }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field span-12 last">
  <%= f.label :email, :class => "span-3" %>
  <%= f.text_field :email, :class => "span-9 last" %>
</div>
<div class="field span-12 last">
  <%= f.label :password, :class => "span-3" %>
  <%= f.password_field :password, :class => "span-9 last" %>
</div>
<div class="field span-12 last">
  <%= f.label :password_confirmation, :class => "span-3" %>
  <%= f.password_field :password_confirmation, :class => "span-9 last" %>
</div>
<div class="actions span-12 last">
  <%= f.submit %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to 'Back', home_path %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Users</h2>

<table>
  <tr>
    <th>Password</th>
    <th>Salt</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.password %></td>
    <td><%= user.salt %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="ltl-form-title prepend-6 span-12 append-6 last">
  <h2>Sign up</h2>
</div>

<div class="span-12 prepend-6 append-6 last">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>