config/routes.rb
Lotl::Application.routes.draw do

  get "whatsandwhys" => 'info#whatsandwhys', :as => 'whats_and_whys'

  match "/home" => 'entrance#home', :via => 'get', :as => 'home'
  match "/login" => 'entrance#login', :via => 'post', :as => 'login'
  match "/activation_instructions" => "entrance#activation_instructions", :via => 'get', :as => 'activation_instructions'
  match "/activate" => "entrance#activate", :via => 'get', :as => 'activate'

  resources :users, :only => [:new, :create]
  resources :feedback, :only => [:new, :create]

  resources :projects do
    resources :tasks
    resources :collaborators, :only => [:create, :destroy]
    resources :statistics, :only => [:index, :show]
  end

  root :to => "entrance#home"

end

app/models/project.rb
# == Schema Information
# Schema version: 20110703011409
#
# Table name: projects
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  repository :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Project < ActiveRecord::Base
  has_many :tasks
  has_and_belongs_to_many :users
  default_scope :order => 'projects.name'

  attr_accessible :name, :repository

  validates :name, :presence => true,
                  :length => {:maximum => 255}

  validates :repository, :format => {:with => /^git@github.com:\w+\/\w+\.git$/, :allow_nil => true}

  def repository=(repo)
    return nil if repo.blank?
    return repo
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize, :only => [:edit, :update, :destroy]

  # Here we get the prjects and the most recent task activity from that 
  # project. The definition of the recent task activity is At:T E 
  # t1.modified_at > t2.modified_at & n <= 3
  def index
    @projects = current_user.projects
    @project_tasks = recently_active_tasks(@projects)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    set_current_project

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    set_current_project
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    @project.users << current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to(projects_path) }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { 
          flash[:error] = @project.errors.full_messages[0] if not @project.valid?
          redirect_to(projects_path)
        }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(projects_path, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end

  rescue ActiveRecord::StaleObjectError
    flash[:error] = t "flash.msg.project-stale-object"
    redirect_to(projects_path)
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    # @project = Project.find(params[:id])
    # @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end

  private
  
  # recently_active_tasks :: [{project -> [task]}]
  def recently_active_tasks(ps)
    temp = {}
    ps.each do |p|
      ts = Task.where("project_id = ?", p.id).order("updated_at DESC").limit(3)
      temp[p] = ts
    end
    return temp
  end

  def authorize
    p = Project.find(params[:id])
    if not p.users.include?(current_user)
      flash[:notice] = t("flash.msg.access-denied")
      redirect_to home_path
    end
  end

  def set_current_project
    session[:project_name] = @project.name
  end

end

# error: missed a 'end' when copying code into this file

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_collaborators.html.erb
<% @project.users.each do |u| %>
<div class="span-7 last">
  <%= u.email %>&nbsp;&nbsp;
  <%= link_to t(".remove"), project_collaborator_path(@project, u), :method => :delete %>
</div>
<% end %>

<%# form to add a new user %>
<%= form_for(User.new, :url => project_collaborators_path(@project)) do |f| %>
<div class="field span-7 last">
  <%= f.text_field :email %>
  <%= f.submit t(".add-collaborator") %>
</div>  
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field span-10 last">
    <%= f.label :name, :class => "span-3" %>
    <%= f.text_field :name, :class => "span-7 last" %>
  </div>
  <div class="field">
    <%= f.label :repository, :class => "span-3" %>
    <%= f.text_field :repository, :class => "span-7 last" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="ltl-form-title prepend-3 span-18 append-3 last">
  <h2><%= t ".edit-project" %></h2>

  <div class="span-10">
    <h3 class="subpoint"><%= t ".settings" %></h3>
    <%= render 'form' %>
  </div>

  <div class="prepend-1 span-7 last">
    <h3 class="subpoint"><%= t ".collaborators" %></h3>
    <%= render 'collaborators' %>
  </div>
  
  <div class="span-16">
      <%= link_to t(".back"), projects_path %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="ltl-projects-list span-15">
  <h2 class="heading"><%= t ".your-projects" %></h2>
  <h5 class="span-4"><%= t ".name" %></h5>
  <h5 class="span-9"><%= t ".recent-activity" %></h5>
  <h5 class="span-2 last"><%= t ".actions" %></h5>
  <hr/>

  <% @projects.each do |project| %>
  <div class="ltl-project-summary span-15 last">
    <div class="span-4">
      <h3>
	<%= link_to project.name, project_tasks_path(project) %>
      </h3>
    </div>

    <div class="ltl-project-tasks span-9">
      <% if @project_tasks[project].empty? %>
      <p><%= t ".none" %></p>
      <% else %>
        <% @project_tasks[project].each do |tsk| %>
        <div>
	  <strong>[</strong>&nbsp;<%= t(".#{tsk.progress}") %>&nbsp;<strong>]</strong>
	  <%= tsk.title %>
	</div>
        <% end %>
      <% end %>
    </div>

    <div class="span-2 last">
      <%= link_to "#{t '.edit'}", edit_project_path(project) %>
    </div>
  </div>
  <hr/>
  <% end %>

</div>

<div class="span-8 prepend-1 last">
  
  <div class="ltl-project-action span-8 last">
    <h2 class="heading"><%= t ".create-a-project" %> </h2>

    <%= form_for(Project.new) do |f| %>
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => "span-8" %><br/>
    <%= f.label :repository %><br/>
    <%= f.text_field :repository, :class => "span-8" %><br/>
    <%= f.submit %>
    <% end %>
  </div>
  
</div>

<%# error: forgot to add closing erb tag %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Repository:</b>
  <%= @project.repository %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>