config/routes.rb
Lotl::Application.routes.draw do

  get "whatsandwhys" => 'info#whatsandwhys', :as => 'whats_and_whys'

  match "/home" => 'entrance#home', :via => 'get', :as => 'home'
  match "/login" => 'entrance#login', :via => 'post', :as => 'login'
  match "/activation_instructions" => "entrance#activation_instructions", :via => 'get', :as => 'activation_instructions'
  match "/activate" => "entrance#activate", :via => 'get', :as => 'activate'

  resources :users, :only => [:new, :create]
  resources :feedback, :only => [:new, :create]

  resources :projects do
    resources :tasks
    resources :collaborators, :only => [:create, :destroy]
    resources :statistics, :only => [:index, :show]
  end

  root :to => "entrance#home"

end

app/views/layouts/_footer.html.erb
<footer class="span24 last">
  <div class="span-12">
    <div class="ltl-footer-bin">
      <%= link_to t('.whats-and-whys'), whats_and_whys_path %>
    </div>
  </div>
  <div class="span-12 last">
    <div class="ltl-footer-bin ltl-footer-bin-last">
    <%= link_to t('.contact-us'), new_feedback_path %>
    </div>
  </div>

    <!-- Scripts concatenated and minified via ant build script-->
    <!-- end scripts-->
    <%= javascript_include_tag :defaults %>

    <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
</footer>

app/views/layouts/_header.html.erb
<header class="span-24 last">
     <% logo = image_tag 'lotl-logo.png' %>
     <%= link_to logo, home_path, :alt => "Law of the Loop" %>

  <% if show_menu?(params) %>
  <div class="span-24 ltl-menu last">
    <nav class="ltl-project-menu span-24 last">
      <% if show_current_project? %>
        <span class="ltl-current-project">
  	<%= current_project %>:
        </span>
      <% end %>
      <%= link_to t(".dashboard"), projects_path %>
      <% if show_task_selections?(params) %>
        <%= link_to t(".tasks"), project_tasks_path(params[:project_id]) %>
	<%= link_to t(".statistics"), project_statistics_path(params[:project_id]) %>
      <% end %>
    </nav>

    <!-- <nav class="ltl-application-menu span-3 last"> -->
    <!--   <%= link_to t(".dashboard"), projects_path %> -->
    <!-- </nav> -->
  </div>
  <% end %>

</header>

app/views/layouts/admin_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LOOP Admin Message</title>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="project management for continuous deployment">
    <meta name="author" content="marco">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="project management, law of the loop, continuous deployment, continuous delivery">

    <title>Law of the Loop</title>
    <%= stylesheet_link_tag "style", :media => "all" %>
    <%= stylesheet_link_tag "blueprint/screen", :media => "screen, projection" %>
    <%= stylesheet_link_tag "blueprint/print", :media => "print" %>
    <!--[if lt IE 8]>
    <%= stylesheet_link_tag "blueprint/ie", :media => "screen, projection" %>
    <![endif]-->
    <%# stylesheet_link_tag "smoothness/jquery-ui-1.8.14.custom" %>

    <%= javascript_include_tag "libs/modernizr-2.0.min" %>
    <%= javascript_include_tag "libs/respond.min-9b9d486" %>
    <%= javascript_include_tag "libs/protovis.min-3.3.1" %>
    <%= csrf_meta_tag %>

  </head>
  <body class="bg-grey">
    <div id="wrapper">

      <div class="header-grey">
	<div class="container">
	     <%= render "layouts/header" %>
        </div>
        <hr class="header-border"/>
      </div>

      <div class="container showgri">

      <% flash.each do |k, v| %>
      <div class="ltl-flash span-8 last <%= k.to_s %>" style="margin-left:310px; margin-right:310px">
	<%= v %>
      </div>
      <% end %>

      <%= yield %>


      </div>
      <div id="push"></div>
    </div>

    <div id="footer" class="footer-grey">
      <div class="container showgri">
      <%= render "layouts/footer" %>
      
      <% if Rails.env.development? %>
      <div class="span-24 last">
	<%= debug(params) %>
	<%= debug(session) %>
      </div>
      <% end %>
      </div>
    </div>
    
  </body>
</html>